### ISSUE TITLE
Finagle adjuster - Add timestamp and duration if missing

### ISSUE THREAD

**Issue by naoman** [openzipkin/zipkin-sparkstreaming#25]
Currently in [Finagle Adjuster](https://github.com/openzipkin/zipkin-sparkstreaming/blob/master/adjuster/finagle/src/main/java/zipkin/sparkstreaming/adjuster/finagle/FinagleAdjuster.java) we apply timestamp and duration to a span only if it contains a binary annotation with the key "finagle.version".

Some legacy instrumentation libraries also use [finagle thrift schema](https://github.com/twitter/finagle/blob/06908573ecd71a9142c3992d5671e4b4c772e922/finagle-thrift/src/main/thrift/tracing.thrift) and don’t have timestamp and duration fields populated for the Spans. We should add an adjuster that can be used to fill these fields, if they are empty, irrespective of binary annotation availability.

**Comment by naoman** [comment]
We can add a property zipkin.sparkstreaming.adjuster.finagle.alwaysApplyTimestampAndDuration for this feature. 
@adriancole thoughts? I can make the change and send a PR.

**Comment by adriancole** [comment]
You mean instead of only when it is a finagle span? Easier for email review
to know what happens now and what would be different

**Comment by naoman** [comment]
```java
public abstract class FinagleAdjuster extends Adjuster {

  abstract boolean issue123();
  abstract boolean issue456();


  @Override protected boolean shouldAdjust(Span span) {
    if (issue123() && containsIssue123(span)) return true;
    if (issue456() && containsIssue456(span)) return true;
    return false;
  }

  @Override protected Span adjust(Span span) {

    Span returnSpan = span;

    if (issue123()) {
      returnSpan = patchIssue123(returnSpan);
    }

    if (issue456()) {
      return returnSpan = patchIssue456(returnSpan);
    }

    return returnSpan;
  }
}
````

**Comment by naoman** [comment]
And we can have class Issue123 and Issue456 then implements containsIssue123 and patchIssue123

**Comment by adriancole** [comment]
@naoman yep this will work for up to probably 3 adjustments, after which would need to be refactored into a composite I think.

**Comment by adriancole** [comment]
our finagle adjuster currently supports this
