### ISSUE TITLE
Finagle adjuster - drop finagle flush annotation

### ISSUE THREAD

**Issue by naoman** [openzipkin/zipkin-sparkstreaming#26]
This is related to [this](https://github.com/twitter/finagle/issues/343) bug in finagle memcached library where the duration of a span ends up being more than the actual value because a span is submitted a two times. [This](https://github.com/twitter/finagle/pull/516) pull request also has some details.

We should add a finagle adjuster that can fix this issue by dropping "finagle.flush" annotation. This adjuster should be applied before applying timestamp and duration.

**Comment by adriancole** [comment]
Cool. It will be nice to see if the impl can be precise about the memcached
case (so that flush is only dropped here, as otherwise it would hide other
bugs)

**Comment by naoman** [comment]
Unfortunately there is no other annotation or binary annotation that we can used to check if finagle.flush is coming from memcached or not. The only thing we can do is add a warning in the feature documentation.

**Comment by naoman** [comment]
[This](https://github.com/openzipkin/zipkin-sparkstreaming/commit/6ef6693ba0eefe7ee93b4aa2c805c541c77a783d) commit has the changes. To make sure we drop finagle.flush annotation for just memcache traces, we look for presence of "Hit" or "Miss" binary annotation in the Span.
