### ISSUE TITLE
AWS Kinesis stream here or zipkin-aws?

### ISSUE THREAD

**Issue by devinsba** [openzipkin/zipkin-sparkstreaming#28]
I wrote a small little http:zipkin-server -> kinesis relay last night so I can get spans into kinesis. I'm planning to write a kinesis stream source. Should I contribute that in this repo or in aws-zipkin?

/cc @adriancole

**Comment by adriancole** [comment]
> I wrote a small little http:zipkin-server -> kinesis relay last night so
I can get spans into kinesis. I'm planning to write a kinesis stream
source. Should I contribute that in this repo or in aws-zipkin?

Gosh thats a good question. Suppose it should be fine in zipkin-aws as for
example reporter is a different thing than collector and both are already
there. The common thread on zipkin-aws is aws expertise so yeah.. think so!

**Comment by devinsba** [comment]
https://github.com/openzipkin/zipkin-aws/pull/34 is almost ready, closing this issue
