### ISSUE TITLE
Add KafkaStream

### ISSUE THREAD

**Issue by adriancole** [openzipkin/zipkin-sparkstreaming#7]
We should add a KafkaStreamFactory placed under..
stream/kafka
autoconfigure/stream-kafka

The README, pom files, project structure and code style should be the same as #6 

The code itself should be similar to #3, using the same property name conventions from zipkin-collector-kafka. Don't forget tests!

https://github.com/openzipkin/zipkin/blob/master/zipkin-collector/kafka/src/main/java/zipkin/collector/kafka/KafkaCollector.java
https://github.com/openzipkin/zipkin/blob/master/zipkin-collector/kafka/src/test/java/zipkin/collector/kafka/KafkaCollectorTest.java

https://github.com/openzipkin/zipkin/tree/master/zipkin-autoconfigure/collector-kafka/src/main/java/zipkin/autoconfigure/collector/kafka
https://github.com/openzipkin/zipkin/tree/master/zipkin-autoconfigure/collector-kafka/src/test/java/zipkin/autoconfigure/collector/kafka
https://github.com/openzipkin/zipkin/blob/master/zipkin-collector/kafka/README.md

**Comment by naoman** [comment]
#11 has the changes.
